Feature/at un 16
at-internship/at-university-ui pull request #13
Opened 2020-10-13 20:28 UTC by BrendaMorales9719

2020-10-13 22:05 UTC, at-internship requested changes

2020-10-13 22:05 UTC, at-internship commented on src/views/layouts/main.hbs
> +    <title>AT ::: UI</title>
AT ::: UNIVERSITY

2020-10-13 22:05 UTC, at-internship commented on src/views/partials/navigation.hbs
> +                    <a class="nav-link" href="/users/home">
We don't have "home" should be `<a class="nav-link" href="/dashboard">`

2020-10-13 22:05 UTC, at-internship commented on src/views/partials/navigation.hbs
> +                            <img src="/img/icons/menu-home-icon.png" title="Home" class="icons">
`<img src="/img/icons/menu-home-icon.png" title="Dashboard" class="icons">`

2020-10-13 22:05 UTC, at-internship commented on src/views/partials/navigation.hbs
> +                {{#if user}}
Add Code comment <!-- -->

2020-10-13 22:05 UTC, at-internship commented on src/views/partials/navigation.hbs
> +                {{/if}}
Add Code comment <!-- -->

2020-10-13 22:05 UTC, at-internship commented on src/views/partials/navigation.hbs
> +            <ul class="navbar-nav ml-auto">
For now, comment this section, Add Code comment <! - ->

2020-10-14 15:25 UTC, pinto1997 approved these changes

2020-10-14 17:06 UTC, at-internship approved these changes

2020-10-14 17:15 UTC, merged