it was renamed the functions existing and add new functions without f…
at-internship/at-university-ui pull request #18
Opened 2020-10-15 15:55 UTC by Efcobr-AT

US 17: Migrate Admin controller

2020-10-15 17:19 UTC, fasaga approved these changes

2020-10-16 14:15 UTC, at-internship requested changes

2020-10-16 14:15 UTC, at-internship commented on src/controllers/admin.controller.js
> +const { getAllCourses } = require("../services/course.service");
Take a look

```
// MICROSERVICE - HEROKU - UNIVERSITY
const universityServiceAPI = require("../services/at-iniversity-api.service");
```

2020-10-16 16:58 UTC, at-internship approved these changes
Approved

2020-10-16 17:03 UTC, merged