Update admin.routes.js
at-internship/at-university-ui pull request #19
Opened 2020-10-15 17:05 UTC by Yairmar

2020-10-15 17:37 UTC, fasaga approved these changes

2020-10-16 14:12 UTC, at-internship requested changes

2020-10-16 14:12 UTC, at-internship commented on src/routes/at-university.routes.js
>  //Get Dashboard
Should be // AT-UNIVERSITY-UI - Dashboard

2020-10-16 14:12 UTC, at-internship commented on src/routes/admin.routes.js
> +router.get("/admin", renderIndexAdmin);
Should be `router.get("/", renderIndexAdmin);`

2020-10-16 14:12 UTC, at-internship commented on src/routes/admin.routes.js
> +router.get("/admin/course", renderCourseList);
Should be `router.get("/course", renderCourseList);`

2020-10-16 17:00 UTC, at-internship approved these changes
Approved

2020-10-16 17:03 UTC, merged