delete course
at-internship/at-university-ui pull request #27
Opened 2020-11-04 22:03 UTC by hgglez

done

2020-11-05 14:13 UTC, at-internship commented
This branch should be `feature/AT-UN-UI-Delete-Admin-Course`

2020-11-05 23:07 UTC, at-internship requested changes

2020-11-05 23:07 UTC, at-internship commented on src/controllers/admin.controller.js
> -    res.render("admin/index");
This is not a valid change (blank space or indent code),  is this a new functionality?, if not there is no point in modifying it

2020-11-06 15:39 UTC, at-internship approved these changes
approved

2020-11-06 23:28 UTC, raaul-at approved these changes

2020-11-09 15:11 UTC, merged