feature/AT-UN-UI-Unit-Test-Admin un UI unit test admin
at-internship/at-university-ui pull request #37
Opened 2020-12-04 15:40 UTC by acones96

2020-12-04 15:42 UTC, raaul-at approved these changes

2020-12-04 16:40 UTC, raaul-at approved these changes

2020-12-08 19:17 UTC, at-internship requested changes

2020-12-08 19:17 UTC, at-internship commented on package.json
> +        "test": "mocha src/test/**/*.js",
Should be "test": "mocha src/test/**/*.test.js"

2020-12-08 19:52 UTC, at-internship approved these changes
Approved

2020-12-08 22:40 UTC, merged