Feature/at un 15
at-internship/at-university-ui pull request #4
Opened 2020-10-01 14:16 UTC by Yairmar

2020-10-01 14:28 UTC, at-internship requested changes
Please take a look

2020-10-01 14:28 UTC, at-internship commented on src/config.js
> +//AT_UNIVERSITY_SERVICE_URI: https://at-university-api.herokuapp.com/api
Please remove commented code

2020-10-01 14:49 UTC, fasaga approved these changes

2020-10-02 16:15 UTC, JesusMeraz-AT approved these changes

2020-10-02 17:53 UTC, closed without merging

2020-10-02 17:53 UTC, fasaga commented
CLOSING THIS PULL REQUEST, CHANGES WERE ADDED TO ANOTHER PR