Create dashboard page
at-internship/at-university-ui pull request #8
Opened 2020-10-02 22:03 UTC by maria201429

Creation of dashboard to view all courses.

2020-10-05 14:00 UTC, at-internship commented on src/routes/course.routes.js
> +const { getAllCourses } = require ('../controllers/TestController');
should be test.controller.js

2020-10-05 14:00 UTC, at-internship commented on src/routes/course.routes.js
> +router.get("/course",getAllCourses);
router.get("/course", getAllCourses);

2020-10-05 14:02 UTC, at-internship requested changes
Please verify, we have some comments

2020-10-06 15:50 UTC, fasaga approved these changes

2020-10-06 15:50 UTC, fasaga commented on src/routes/course.routes.js
> +//Get All Courses
Remove these 2 lines, we do not need them

2020-10-06 15:50 UTC, fasaga commented on src/routes/course.routes.js
> +const { getAllCourses } = require ('../controllers/TestController');
Remove this line

2020-10-06 15:50 UTC, fasaga commented on src/controllers/dashboard.controller.js
> +/*This is a test controller for course service*/
Remove this line

2020-10-06 15:50 UTC, fasaga commented on src/controllers/courses.controller.js
> +const { getAllCourses } = require("../services/course.service");
Leave this file empty, do not forget to remove also the references to its functions

2020-10-07 13:32 UTC, fasaga commented
@at-internship Could you please approve this pull request?

2020-10-07 14:47 UTC, at-internship approved these changes
Approved

2020-10-07 14:49 UTC, merged